### ISSUE TITLE
Unhandled exception in script: Traceback is disabled via bootloader option.

### ISSUE THREAD

**Issue by Kiriru777** [Gdalik/EarQuiz_Frequencies#6]
The program exits with modal window "Unhandled exception in script:": Traceback is disabled via bootloader option.

WIndows 10 64bit.

**Comment by Gdalik** [comment]
Can you give me more details, what you do and when this happens?

**Comment by Gdalik** [comment]
@Kiriru777, do you use the latest version (0.1.6)? I fixed some startup issues that used to occur, and now I cannot reproduce it in none of my systems. Everything starts fine no matter which audio driver or audio device I use.

As for the exception we are discussing here, it's not a bug, it's a feature :-).
I prevent the program from running multiple times in parallel, cluttering up the task manager, etc.

If you want to change this behavior, just comment out the following lines in the `main.py` file:

`from tendo.singleton import SingleInstance`
and
`    me = SingleInstance()`

And then try to rebuild the app, using the instructions in the README file.
You will be able to run multiple copies of the app in parallel then.
But I wouldn't recommend that.

**Comment by Kiriru777** [comment]
Yes, I do use version 0.1.6.

**Comment by Kiriru777** [comment]
BTW, at this very time I am trying to start it in venv after cloning. No luck :( 

The program shows its interface and closes.

**Comment by Kiriru777** [comment]
![freqs](https://github.com/user-attachments/assets/54800908-d6c2-479d-8022-dd390687ce71)

**Comment by Gdalik** [comment]
Try to uninstall PyQt6 and install the latest version of this library.
Or clone [this branch](https://github.com/Gdalik/EarQuiz_Frequencies/tree/version-0.1.7) and try to start it in the fresh venv from scratch.
It's the latest version which I'm going to build and release for all the supported platforms by the end of the months.
And it has some new interesting features...

**Comment by Gdalik** [comment]
Also, what version of Python do you use?

**Comment by Kiriru777** [comment]
Python 3.10.6

**Comment by Kiriru777** [comment]
I have just:
1. cloned 0.1.7
2. created clean venv
3. pip install -r requirements.txt ["Using cached ..."]
4. py -m main

Same result: after showing the interface, the progream quits.

**Comment by Gdalik** [comment]
Can you delete or move somewhere the `Playlists` folder and the `config.ini` file in the 'EarQuiz\Frequencies' folder, which is inside the Application Data folder ('AppData' or 'AppData\Roaming') of your system User folder, and try again?

**Comment by Kiriru777** [comment]
1. I renamed Playlists folder, renamed config.ini in Users\Kiriru777\Appdata\Roaming\EarQuiz\Frequencies --- no result, the program won't start.
2. I renamed Frequencies folder. New Frerquencies folder appeared --- no luck again.

**Comment by Kiriru777** [comment]
Also, I reinstalled from scratch PyQt6

**Comment by Gdalik** [comment]
Honestly, I cannot reproduce this problem on neither Windows 10 nor Windows 11...

**Comment by Kiriru777** [comment]
![freqs2](https://github.com/user-attachments/assets/31c6e867-21a0-4c99-a8d9-13bfa332bd84)

**Comment by Gdalik** [comment]
It's strange that it installs the old version of the `requirements.txt` file.
The one in the 0.1.7 branch doesn't contain darkdetect dependency, and the version conditions for PyQt6 are different.
Have you tried to reinstall it from scratch with '--no-cache-dir' option?

**Comment by Kiriru777** [comment]
I have just tried  '--no-cache-dir' option with same lack of any positive result.

**Comment by Kiriru777** [comment]
Yet another thing to mention, when I start the newly configured EarQuiz, it does create Frequencies folder. But the folder is empty, no ini file or whatever.

**Comment by Kiriru777** [comment]
main.py, line 42 mw = MainWindowContr(). It quits there

**Comment by Gdalik** [comment]
@Kiriru777, I have finally reproduced this issue.
On Windows 10 64 bit, the app exits with code -1073741819 (0xC0000005) when pedalboard v0.9.7+ tries to load any audio file.
There is something weird in the library behavior, probably caused by the upgrade to NumPy v2, which should be investigated...
It works fine on macOS, though...
Try to reinstall pedalboard with

`pip install pedalboard<=0.9.6`

**Comment by Kiriru777** [comment]
Oh! That really worked! Thank you!

I suggest split this topic into two for future references:
1) Sometimes program won't start under Window 10; and
2) The program does not start under Python.

Also, you mentioned this version is 0.1.7, but the info in all parts (startup, help/about) says 0.1.6.

**Comment by Kiriru777** [comment]
```pip install 'pedalboard<=0.9.6'``` ('pedalboard' and '<=0.9.6' in single quotes)
Maybe include this line in requirements.txt?

**Comment by Gdalik** [comment]
> Also, you mentioned this version is 0.1.7, but the info in all parts (startup, help/about) says 0.1.6.

I think you have either cloned or run the wrong branch (master instead for 0.1.7). It is updated...

**Comment by Gdalik** [comment]
> ```pip install 'pedalboard<=0.9.6'``` ('pedalboard' and '<=0.9.6' in single quotes)
> Maybe include this line in requirements.txt?

I have already updated the requirements.txt in both master and 0.1.7 repositories.
